# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Óscar Oliveira
url:              https://oscar-oliveira.github.io
baseurl:          "/site"

author:
  name:           'Óscar Oliveira'
  url:            https://oscar-oliveira.github.io/

plugins:          [jekyll-paginate]
paginate:         5
