# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Óscar Oliveira1
url:              https://oscar-oliveira.github.io/blog/blog/
baseurl:          /blog/

author:
  name:           'Óscar Oliveira'
  url:            https://oscar-oliveira.github.io/

plugins:          [jekyll-paginate]
paginate:         5
